require "base"
require "pluggs.lsp"
require "pluggs.tree-sitterConf"
require "pluggs.lualineConf"
require "pluggs.cmpConf"
require "pluggs.nvim-treeConf"
require "pluggs.telescopeConf"
require "pluggs.ftermConf"
require "pluggs.gitsignsConf"
require "pluggs.autopairsConf"
require "pluggs.null-lsConf"
require "pluggs.dapConf"
require "pluggs.miniConf"
require "pluggs.telekastenConf"
-- require "pluggs.neorgConf"
-- require "pluggs.whichkeyConf"
